#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13
PROOF_DRY_RUN="${CREDENTIALED_PROOF_DRY_RUN:-0}"

probe() {
  if [[ "$PROOF_DRY_RUN" == "1" ]]; then
    note "dry-run: skipped credentialed probe $1"
  else
    pnpm credentialed-proof:probe -- "$1"
  fi
}

banner "Sachkov Inside Telegram credentialed proof"

stage "Scope and destinations"
say "This temporary proof writes secrets and provider identifiers only to ignored $ENV_FILE."
step "BotFather produces TELEGRAM_BOT_TOKEN; getMe verifies TELEGRAM_PROOF_BOT_ID and TELEGRAM_PROOF_BOT_USERNAME."
step "The closed chat produces TELEGRAM_CANONICAL_CHAT_ID; the temporary callback produces TELEGRAM_PROOF_WEBHOOK_URL."
step "Webhook and Platform integration credentials are written only to $ENV_FILE and matching temporary Platform configuration."
step "Redacted observations go to ignored .credentialed-proof/evidence.json; recovery references are never persisted by this wizard."
step "No GitHub secret, production environment, external message campaign, deploy, or production traffic is changed."
if [[ "$PROOF_DRY_RUN" != "1" ]] && ! confirm "Continue with this exact scope and these destinations?"; then
  warn "proof cancelled before any credential was captured"
  exit 1
fi

stage "BotFather identity"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_BOT_TOKEN="123456:non_secret_fixture_token_abcdefghijklmnopqrstuvwxyz"
  TELEGRAM_PROOF_BOT_USERNAME="inside_fixture_bot"
else
  open_url "https://t.me/BotFather"
  step "Send /newbot, create a dedicated temporary Sachkov Inside proof bot, and copy its token."
  ask_secret TELEGRAM_BOT_TOKEN "Paste the temporary bot token (hidden):"
  step "Copy the exact username BotFather assigned, without changing the bot or token."
  ask TELEGRAM_PROOF_BOT_USERNAME "Bot username (with or without @):"
fi
if [[ ! "$TELEGRAM_BOT_TOKEN" =~ ^[1-9][0-9]{5,}:[A-Za-z0-9_-]{20,}$ ]]; then
  warn "token shape is not a Telegram Bot API token"
  exit 1
fi
TELEGRAM_PROOF_BOT_ID="${TELEGRAM_BOT_TOKEN%%:*}"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_PROOF_BOT_ID "$TELEGRAM_PROOF_BOT_ID"
write_env TELEGRAM_PROOF_BOT_USERNAME "$TELEGRAM_PROOF_BOT_USERNAME"
probe verify-bot

stage "Closed chat and minimum administration"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_CANONICAL_CHAT_ID="-1001234567890"
else
  open_url "https://web.telegram.org/"
  step "Create a temporary private group, add only the proof participants, and add the dedicated bot."
  step "Promote the bot to administrator; disable every optional permission the client permits while retaining administrator status."
  step "Send /proof_chat_id in that group so getUpdates can discover it before webhook setup."
  pause "Press Enter after the group update is visible"
  TELEGRAM_CANONICAL_CHAT_ID="$(pnpm --silent credentialed-proof:probe -- capture-chat-id)"
fi
write_env TELEGRAM_CANONICAL_CHAT_ID "$TELEGRAM_CANONICAL_CHAT_ID"
probe verify-chat

stage "Temporary application and Platform seam"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  TELEGRAM_PROOF_WEBHOOK_URL="https://proof.invalid/webhooks/telegram"
  PLATFORM_EVIDENCE_DELIVERY_URL="https://platform-proof.invalid/integrations/telegram/v1/membership-evidence"
  PLATFORM_INTEGRATION_SECRET="non_secret_fixture_platform_link"
  PLATFORM_EVIDENCE_DELIVERY_SECRET="non_secret_fixture_evidence"
else
  step "Start the task database and Telegram application from this checkout; expose only /webhooks/telegram through a temporary HTTPS endpoint."
  ask TELEGRAM_PROOF_WEBHOOK_URL "Full temporary HTTPS webhook URL:"
  step "Start the temporary Platform consumer and copy its Membership Evidence endpoint."
  ask PLATFORM_EVIDENCE_DELIVERY_URL "Temporary Platform evidence URL:"
  step "Copy the matching temporary Platform→Telegram linking bearer."
  ask_secret PLATFORM_INTEGRATION_SECRET "PLATFORM_INTEGRATION_SECRET (hidden):"
  step "Copy the separate matching Telegram→Platform evidence bearer."
  ask_secret PLATFORM_EVIDENCE_DELIVERY_SECRET "PLATFORM_EVIDENCE_DELIVERY_SECRET (hidden):"
fi
TELEGRAM_WEBHOOK_SECRET="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("base64url"))')"
write_env TELEGRAM_PROOF_WEBHOOK_URL "$TELEGRAM_PROOF_WEBHOOK_URL"
write_env PLATFORM_EVIDENCE_DELIVERY_URL "$PLATFORM_EVIDENCE_DELIVERY_URL"
write_env PLATFORM_INTEGRATION_SECRET "$PLATFORM_INTEGRATION_SECRET"
write_env PLATFORM_EVIDENCE_DELIVERY_SECRET "$PLATFORM_EVIDENCE_DELIVERY_SECRET"
write_env PLATFORM_EVIDENCE_DELIVERY_MODE live
write_env TELEGRAM_DELIVERY_MODE live
write_env TELEGRAM_MEMBERSHIP_MODE live
write_env TELEGRAM_WEBHOOK_SECRET "$TELEGRAM_WEBHOOK_SECRET"
write_env WORKERS_ENABLED true
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "Run pnpm db:migrate, then start or restart Telegram and the temporary Platform consumer with these exact values."
  pause "Press Enter when both applications and the HTTPS endpoint are healthy"
fi

stage "Webhook contract"
step "Keep the application and HTTPS endpoint running. The probe sets only message, my_chat_member, and chat_member updates with the separate secret token."
probe configure-webhook
probe verify-webhook-auth
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "Send one ordinary message in the proof group and confirm it reaches the application."
  pause "Press Enter after the update is acknowledged"
fi

stage "Webhook auth, durability, retry, and deduplication"
step "Send synthetic no-PII updates to the callback with missing, wrong, and correct secret headers; missing/wrong must reject and correct must return 2xx only after inbox commit."
step "Repeat the same synthetic update_id and confirm the durable inbox remains unique."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  step "Stop the callback, trigger one proof-chat update, wait for Telegram getWebhookInfo to record delivery failure, then restart the callback."
  pause "Press Enter after Telegram has attempted delivery while the callback is stopped"
fi
probe observe-webhook-outage
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after the callback is running and Telegram has retried"
fi
probe verify-webhook-recovered
probe snapshot

stage "Ordinary and tokenized /start"
step "In a private chat with the bot, run ordinary /start and confirm Contactability plus a durable response delivery."
step "From authenticated temporary Platform Accounts, exercise a valid token, expired token, replay, concurrent consume, same-identity repeat, and conflicting Account."
step "Confirm no raw token, username, email, or provider payload appears in the database or evidence file."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after all linking outcomes have been observed"
fi
probe snapshot

stage "Membership events and reconciliation"
step "Observe member/restricted/left/kicked or other reachable statuses and record the normalized outcome, not the raw identity."
step "Remove and rejoin the linked subject; prove newer removal denies and newer rejoin restores."
step "Suppress one removal event, then allow reconciliation to repair it without extending stale positive evidence."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after event and reconciliation evidence is complete"
fi
probe snapshot

stage "Administrator loss and provider outage"
step "Demote the bot, trigger a membership read, and confirm degraded/unavailable fail-closed behavior."
step "Restore the exact minimum administrator configuration and confirm a newer observation recovers."
step "Also interrupt provider reachability and confirm access remains local and expires closed."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after demotion, restoration, and outage are recorded"
fi
probe verify-chat
probe snapshot

stage "Blocked send and restored contactability"
step "Block the bot from the temporary user, trigger a response, and record the Bot API rejection only as a delivery diagnostic."
step "Unblock the bot and send a new /start; confirm Contactability and delivery recover without inferring Membership."
if [[ "$PROOF_DRY_RUN" != "1" ]]; then
  pause "Press Enter after block/unblock recovery is recorded"
fi
probe snapshot

stage "Owner-only identity recovery rehearsal"
say "Use only the temporary conflicting Accounts created in this proof. No direct SQL edit is allowed."
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  note "dry-run: skipped owner recovery because fixture references are intentionally absent"
else
  ask RECOVERY_REF "Unique recovery audit reference:"
  ask OPERATOR_REF "Owner/operator reference:"
  ask REASON_REF "Issue/change reference:"
  ask_secret TELEGRAM_IDENTITY_REF "TelegramIdentity reference (hidden):"
  ask_secret SOURCE_ACCOUNT_REF "Current source Principal reference (hidden):"
  ask_secret TARGET_ACCOUNT_REF "Target Principal reference (hidden):"
  ask_secret TARGET_LINK_TRANSACTION_REF "Target conflict transaction reference (hidden):"
  pnpm owner:recover-identity -- --dry-run \
    --recovery-ref "$RECOVERY_REF" --operator-ref "$OPERATOR_REF" --reason-ref "$REASON_REF" \
    --telegram-identity-ref "$TELEGRAM_IDENTITY_REF" --source-account-ref "$SOURCE_ACCOUNT_REF" \
    --target-account-ref "$TARGET_ACCOUNT_REF" --target-link-transaction-ref "$TARGET_LINK_TRANSACTION_REF"
  step "Compare the printed source/target fingerprints with the separately recorded owner values."
  if ! confirm "Execute this transfer on the temporary recovery fixture?"; then
    warn "actual recovery rehearsal is incomplete"
    exit 1
  fi
  ask_secret CONFIRMED_SOURCE_ACCOUNT_REF "Re-enter the source Principal reference (hidden):"
  ask_secret CONFIRMED_TARGET_ACCOUNT_REF "Re-enter the target Principal reference (hidden):"
  pnpm owner:recover-identity -- --execute \
    --recovery-ref "$RECOVERY_REF" --operator-ref "$OPERATOR_REF" --reason-ref "$REASON_REF" \
    --telegram-identity-ref "$TELEGRAM_IDENTITY_REF" --source-account-ref "$SOURCE_ACCOUNT_REF" \
    --target-account-ref "$TARGET_ACCOUNT_REF" --target-link-transaction-ref "$TARGET_LINK_TRANSACTION_REF" \
    --confirm-source-account-ref "$CONFIRMED_SOURCE_ACCOUNT_REF" \
    --confirm-target-account-ref "$CONFIRMED_TARGET_ACCOUNT_REF"
fi
probe snapshot

stage "Redacted evidence handoff"
probe snapshot
step "Give .credentialed-proof/evidence.json to the reviewing agent locally; never paste it into an issue or PR."
step "The reviewer records only boolean outcomes, status vocabulary, counts, timestamps rounded to the proof window, and credential disposal."
step "Do not proceed if any acceptance scenario is missing; rerun the relevant stage instead."

stage "Credential and temporary-resource disposal"
if [[ "$PROOF_DRY_RUN" == "1" ]]; then
  note "dry-run: skipped external disposal and left only non-secret fixture values in the temporary ENV_FILE"
else
  if ! confirm "Delete pending test updates, revoke the bot token, and dispose the temporary chat now?"; then
    warn "proof cannot complete until every ephemeral credential and resource is disposed"
    exit 1
  fi
  probe remove-webhook
  open_url "https://t.me/BotFather"
  step "Send /revoke, select this dedicated proof bot, and revoke the token currently held by the wizard."
  pause "Press Enter after BotFather confirms revocation"
  probe verify-revoked
  step "Delete or leave the temporary closed group according to the recorded disposition; remove the temporary HTTPS endpoint and Platform credentials."
  pause "Press Enter after the chat, endpoint, and matching Platform secrets are disposed"
  write_env TELEGRAM_BOT_TOKEN revoked
  write_env TELEGRAM_WEBHOOK_SECRET disposed
  write_env TELEGRAM_CANONICAL_CHAT_ID disposed
  write_env TELEGRAM_PROOF_WEBHOOK_URL disposed
  write_env PLATFORM_INTEGRATION_SECRET disposed
  write_env PLATFORM_EVIDENCE_DELIVERY_SECRET disposed
fi

finish
